package wortschatz;

import java.awt.Font;
import java.awt.Toolkit;
import java.awt.Window;
import java.io.BufferedReader;
import java.io.DataInputStream;
import java.io.FileInputStream;
import java.io.InputStreamReader;
import java.util.Random;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;


/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainFrame.java
 *
 * Created on 26.Tem.2012, 22:43:18
 */
/**
 *
 * @author Burak
 */
public class MainFrame extends javax.swing.JFrame{

    /** Creates new form MainFrame */
    public MainFrame() {
        try {
            // Set cross-platform Java L&F (also called "Metal")
        UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } 
        catch (UnsupportedLookAndFeelException e) {
           // handle exception
            System.err.println("Error: " + e.getMessage());
        }
        catch (ClassNotFoundException e) {
           // handle exception
            System.err.println("Error: " + e.getMessage());
        }
        catch (InstantiationException e) {
           // handle exception
            System.err.println("Error: " + e.getMessage());
        }
        catch (IllegalAccessException e) {
           // handle exception
            System.err.println("Error: " + e.getMessage());
        }
        
        initComponents();
        
        int x = (Toolkit.getDefaultToolkit().getScreenSize().height/2)-4*this.getHeight()/3;
        int y = (Toolkit.getDefaultToolkit().getScreenSize().width/2)-this.getWidth()/2;
        this.setLocation(y, x);
        
        languageAndWordlistCheckMain();
        loadWordbook();
        writeOnButtons();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Wordschatz 0.1");
        setResizable(false);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton3KeyPressed(evt);
            }
        });

        jButton1.setText("Nächstes Wort >>");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton3KeyPressed(evt);
            }
        });

        jButton2.setText("<< Zurück");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton3KeyPressed(evt);
            }
        });

        jButton3.setText("der Artikel");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton3KeyPressed(evt);
            }
        });

        jButton4.setText("der Plural");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jButton4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton3KeyPressed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jButton5.setText("jButton5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jButton5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton3KeyPressed(evt);
            }
        });

        jProgressBar1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton3KeyPressed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("jLabel1");
        jLabel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton3KeyPressed(evt);
            }
        });

        jMenuBar1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton3KeyPressed(evt);
            }
        });

        jMenu2.setText("Geräte");

        jMenuItem1.setText("Optionen");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("Wortliste Verwaltung");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        jMenu1.setText("Hilfe");

        jMenuItem3.setText("Über");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
    article=0;
    plural = 0;
    word = 0;
    clickCount++;
  
    writeOnButtons();
}//GEN-LAST:event_jButton1ActionPerformed

private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
// TODO add your handling code here:
    new WordAdministrationFrame(this).setVisible(true);
}//GEN-LAST:event_jMenuItem2ActionPerformed

private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
// TODO add your handling code here:
    new OptionsFrame(this).setVisible(true);
}//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(wordCount>0){
            if(article%2 == 0){
                jButton3.setText(selectedWords[order[clickCount%wordCount]][0]);
            }else{
                if(Integer.parseInt(language) == 0){
                    jButton3.setText("der Artikel");
                }else if(Integer.parseInt(language) == 1){
                    jButton3.setText("Artikel");          
                }else if(Integer.parseInt(language) == 2){
                    jButton3.setText("The Article");
                }
                
            }
            article++;
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if(wordCount>0){
            if(plural % 2 == 0){
                jButton4.setText(selectedWords[order[clickCount%wordCount]][2]);
            }else{
                if(Integer.parseInt(language) == 0){
                    jButton4.setText("der Plural");
                }else if(Integer.parseInt(language) == 1){
                    jButton4.setText("Çoğul");         
                }else if(Integer.parseInt(language) == 2){
                    jButton4.setText("The Plural");
                }
            }
            plural++;
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        article=0;
        plural = 0;
        word = 0;
        if(clickCount>0){
            clickCount--;
        }else{
            clickCount = wordCount - 1;
        }

        writeOnButtons();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:        
        if(wordCount>0){
            if(word%2==0){
                jButton5.setText(selectedWords[order[clickCount%wordCount]][3]);
                jButton5.setFont(new Font("tahoma",Font.PLAIN,14));
            }else{
                jButton5.setText(selectedWords[order[clickCount%wordCount]][1]);
                jButton5.setFont(new Font("tahoma",Font.BOLD,22));
            }
            word++;
        }else{
            jButton5.setText(" ");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        new AboutFrame().setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jButton3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton3KeyPressed
        // TODO add your handling code here:
        
        if(evt.getExtendedKeyCode()==49 || evt.getExtendedKeyCode()==103){
            jButton3ActionPerformed(null);
        }
        else if(evt.getExtendedKeyCode()==50 || evt.getExtendedKeyCode()==104){
            jButton5ActionPerformed(null);
        }
        else if(evt.getExtendedKeyCode()==51 || evt.getExtendedKeyCode()==105){
            jButton4ActionPerformed(null);
        }
        else if(evt.getExtendedKeyCode()==37 || evt.getExtendedKeyCode()==100){
            jButton2ActionPerformed(null);
        }
        else if(evt.getExtendedKeyCode()==39 || evt.getExtendedKeyCode()==102){
            jButton1ActionPerformed(null);
        }
    }//GEN-LAST:event_jButton3KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
    
    private String wordbook="";
    private int wordCount;
    private String[][] selectedWords;
    private int[] order;
    private static int clickCount = 0;
    private static int plural = 0;
    private static int article = 0;
    private static int word = 0;
    private String language=""; 
    
    /**
     * @param args the command line arguments
     */
    public void languageAndWordlistCheckMain() {    
            
        try{
            // Open the file that is the first 
            // command line parameter
            FileInputStream fstream = new FileInputStream("Options.dat");
            // Get the object of DataInputStream
            DataInputStream in = new DataInputStream(fstream);
            BufferedReader br = new BufferedReader(new InputStreamReader(in));
            String strLine;
            //Read File Line By Line
            int count =0;
            
            while ((strLine = br.readLine()) != null)   {
                // Print the content on the console
                if(count == 0){
                    wordbook = strLine;
                }else if(count == 1){
                    language = strLine;
                }
                count++;
            }
            //Close the input stream
            in.close();
        }catch (Exception e){//Catch exception if any
            System.err.println("Error: " + e.getMessage());
        }
        
        //prepare the language selected:
        if(Integer.parseInt(language) == 0){
            jButton1.setText("Nächstes Wort>>");
            jButton2.setText("<< Zurück");
            jButton3.setText("der Artikel");
            jButton4.setText("der Plural");
            jMenu1.setText("Hilfe");
            jMenu2.setText("Geräte");
            jMenuItem1.setText("Optionen");
            jMenuItem2.setText("Wortliste Verwaltung");
            jMenuItem3.setText("Über");
        }else if(Integer.parseInt(language) == 1){
            jButton1.setText("Sıradaki Kelime >>");
            jButton2.setText("<< Geri");
            jButton3.setText("Artikel");
            jButton4.setText("Çoğul");
            jMenu1.setText("Yardım");
            jMenu2.setText("Ayarlar");
            jMenuItem1.setText("Seçenekler");
            jMenuItem2.setText("Kelime Listesini Yönet");
            jMenuItem3.setText("Hakkında");            
        }else if(Integer.parseInt(language) == 2){
            jButton1.setText("Next Word >>");
            jButton2.setText("<< Back");
            jButton3.setText("The Article");
            jButton4.setText("The Plural");
            jMenu1.setText("Help");
            jMenu2.setText("Tools");
            jMenuItem1.setText("Options");
            jMenuItem2.setText("Edit Word List");
            jMenuItem3.setText("About"); 
        }
    }
    
    public void loadWordbook(){
        
        selectedWords = new String[5000][4];
        clickCount = 0;
        plural = 0;
        article = 0;
        word = 0;
        wordCount =0;
        
        try{
            //write what has been written
            FileInputStream fstream = new FileInputStream("Words.dat");
            DataInputStream in = new DataInputStream(fstream);
            BufferedReader br = new BufferedReader(new InputStreamReader(in));
          
            String strLine;
            //Read File Line By Line
            int counter = 0;
            String[] info = new String[5];
            while ((strLine = br.readLine()) != null)   {
                if(counter%5 == 0){
                    info[0] = strLine;
                }else if(counter%5 == 1){
                    info[1] = strLine;
                }else if(counter%5 == 2){
                    info[2] = strLine;
                }else if(counter%5 == 3){
                    info[3] = strLine;
                }else if(counter%5 == 4){
                    info[4] = strLine;
                    if(info[4].equals(wordbook) || wordbook.equals("3")){
                        for(int j=0;j<4;j++){
                            selectedWords[wordCount][j] = info[j];
                        }                        
                        wordCount++;                        
                    }
                }
                counter++;
            }
            
            in.close();
        }catch(Exception e){
            System.err.println("Error: " + e.getMessage());
        }
        
        order = new int[wordCount];
        order = orderedToUnordered(wordCount);
        
        jProgressBar1.setMaximum(wordCount);
    }
    
    public void changeWordbook(String s){
        wordbook = s;
    }
    
    public void writeOnButtons(){
        if(Integer.parseInt(language) == 0){
            jButton3.setText("der Artikel");
            jButton4.setText("der Plural");
        }else if(Integer.parseInt(language) == 1){
            jButton3.setText("Artikel");
            jButton4.setText("Çoğul");          
        }else if(Integer.parseInt(language) == 2){
            jButton3.setText("The Article");
            jButton4.setText("The Plural");
        }
        if(wordCount>0){
            jButton5.setText(selectedWords[order[clickCount%wordCount]][1]);
            jButton5.setFont(new Font("tahoma",Font.BOLD,22));
        }else{
            jButton5.setText(" ");
        }
        
        jLabel1.setText((clickCount%wordCount)+1+"/"+wordCount);
        jProgressBar1.setValue(((clickCount%wordCount)+1));
    }

    public int[] orderedToUnordered(int o) {
        Random generator = new Random();
        int[] f = new int[o];
        for(int i=0;i<o;i++){
            int r = generator.nextInt(o);
            boolean isIncluded = false;
            for(int j=0; j<i; j++){
                if(f[j]==r){
                    isIncluded = true;
                }
            }
            
            if(!isIncluded){
                f[i]=r;
            }else{
                i--;
            }            
        }        
        return f;
    }

}

